require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CitiesController do

  # This should return the minimal set of attributes required to create a valid
  # City. As you add validations to City, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all cities as @cities" do
      city = City.create! valid_attributes
      get :index
      assigns(:cities).should eq([city])
    end
  end

  describe "GET show" do
    it "assigns the requested city as @city" do
      city = City.create! valid_attributes
      get :show, :id => city.id.to_s
      assigns(:city).should eq(city)
    end
  end

  describe "GET new" do
    it "assigns a new city as @city" do
      get :new
      assigns(:city).should be_a_new(City)
    end
  end

  describe "GET edit" do
    it "assigns the requested city as @city" do
      city = City.create! valid_attributes
      get :edit, :id => city.id.to_s
      assigns(:city).should eq(city)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new City" do
        expect {
          post :create, :city => valid_attributes
        }.to change(City, :count).by(1)
      end

      it "assigns a newly created city as @city" do
        post :create, :city => valid_attributes
        assigns(:city).should be_a(City)
        assigns(:city).should be_persisted
      end

      it "redirects to the created city" do
        post :create, :city => valid_attributes
        response.should redirect_to(City.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved city as @city" do
        # Trigger the behavior that occurs when invalid params are submitted
        City.any_instance.stub(:save).and_return(false)
        post :create, :city => {}
        assigns(:city).should be_a_new(City)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        City.any_instance.stub(:save).and_return(false)
        post :create, :city => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested city" do
        city = City.create! valid_attributes
        # Assuming there are no other cities in the database, this
        # specifies that the City created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        City.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => city.id, :city => {'these' => 'params'}
      end

      it "assigns the requested city as @city" do
        city = City.create! valid_attributes
        put :update, :id => city.id, :city => valid_attributes
        assigns(:city).should eq(city)
      end

      it "redirects to the city" do
        city = City.create! valid_attributes
        put :update, :id => city.id, :city => valid_attributes
        response.should redirect_to(city)
      end
    end

    describe "with invalid params" do
      it "assigns the city as @city" do
        city = City.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        City.any_instance.stub(:save).and_return(false)
        put :update, :id => city.id.to_s, :city => {}
        assigns(:city).should eq(city)
      end

      it "re-renders the 'edit' template" do
        city = City.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        City.any_instance.stub(:save).and_return(false)
        put :update, :id => city.id.to_s, :city => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested city" do
      city = City.create! valid_attributes
      expect {
        delete :destroy, :id => city.id.to_s
      }.to change(City, :count).by(-1)
    end

    it "redirects to the cities list" do
      city = City.create! valid_attributes
      delete :destroy, :id => city.id.to_s
      response.should redirect_to(cities_url)
    end
  end

end
